### ISSUE TITLE
Error at starting up

### ISSUE THREAD

**Issue by GUEVARA1962** [Chakratos/mhf-save-manager#19]
Thank you for providing such a useful tool.
I've been using a Windows-based server so far, but I'm thinking of switching to an ubuntu desktop-based server.
I tried to use this tool using docker, but I got the following error.
Is there any way to improve it?

os : Ubuntu 22.04.1 LTS
erupe : Ver9.1.1Community Edition
docker ver : 20.10.12
docker compose ver : 2.16.0

[config.php]
const DBNAME = 'erupe02';
const DBUSER = 'postgres';
const DBPASS = 'postgres';
const DBHOST = '127.0.0.1';
const DBDRIVER = 'pdo_pgsql';
const DBPORT = 5432;
const ITEMBOX_ITEMS_READ = 4000; //How many items are shown in the itembox editor: 4000 Items = 40 Pages

[MHF Character Manager.pdf](https://github.com/Chakratos/mhf-save-manager/files/10771545/MHF.Character.Manager.pdf)

**Comment by Chakratos** [comment]
Sorry for the late reply :(

Greetings, it seems that your connection to the PostgreSQL server is not correct.
Connection Refused could mean that because the network is different, PostgreSQL by default blocks all connections from outside.

Here is something that should help you:

https://stackoverflow.com/questions/37809663/postgresql-remote-connection-refused

https://www.bigbinary.com/blog/configure-postgresql-to-allow-remote-connection

**Comment by GUEVARA1962** [comment]
thank you for your reply. 
We will try to confirm the information and respond.

**Comment by GUEVARA1962** [comment]
Due to my lack of knowledge, connection using Docker has not yet been realized :'(
However, I was able to connect to postgresql on ubuntu from windows using zerotear.
Long awaited ubuntu database operation has come true.
Thank you!
